runtime: python39
entrypoint: gunicorn -b :$PORT main:app  # Changed to main:app if that is your Flask app object
instance_class: F4  # This class offers 2GB of memory

automatic_scaling:
  min_idle_instances: 0  # You can adjust this as needed for your application
  max_idle_instances: automatic  # App Engine can manage this based on traffic
  # Removed min_total_instances and max_total_instances

env: standard  # Choose between standard or flexible environment based on your needs

# Removed the empty network: {} section

service: zcor

# Environment variables, if you have any to set
env_variables:
  KEY1: "value1"
  KEY2: "value2"
